// Generated by https://quicktype.io

export interface Address {
    id:         string;
    user_id:    string;
    address_1:  string;
    address_2:  string;
    city:       string;
    state:      string;
    zip:        number;
    name:       string;
    created_at: string;
    updated_at: string;
    deleted_at: null;
}
