// Generated by https://quicktype.io

export interface CartItem {
    id:         string;
    user_id:    string;
    product_id: string;
    quantity:   number;
    created_at: string;
    updated_at: string;
    deleted_at: null;
    product:    Product;
}

export interface Product {
    id:         string;
    name:       string;
    base_price: number;
    images:     string;
}
