// Generated by https://quicktype.io

export interface Product {
	id: string;
	name: string;
	description: string;
	base_price: number;
	quantity: number;
	images: string;
	status: number;
	category: {
		name: string;
	};
	created_at: string;
	updated_at: string;
	deleted_at: string;
}
