// Generated by https://quicktype.io

export interface User {
    id:         string;
    email:      string;
    first_name: string;
    last_name:  string;
    user_name:  string;
    created_at: string;
    updated_at: string;
    deleted_at: string;
}
